%dw 1.0
%output application/java
---
{
	connection_string:"jdbc:postgresql://localhost:5432/postgres&EXTERNAL_DATABASE_NAME=postgres",
	ignored: 0.00,
	considered:10.00,
	failed_measure:null,
	external_server:null,
	external_database:null,
	function:"And",
	failed_score:0.00,
	passed_measure:"N/A",
	filter:null,
	rows_considered:10.00,
	external_column_name:null,
	passed:10.00,
	score:0.00,
	column_name:"First Name",
	pass_range:"100%",
	rows_passed:10.00,
	latest_table_version:9.00,
	table_name:"People",
	name:"Name Exists",
	measure:"N/A",
	rows_ignored:0.00,
	parameters:"Input=First Name    Additional Input=First Name",
	type:null,
	table_created:"2019-01-14 14:50:24.0",
	category:"Conditional",
	last_validated:"2019-01-14 15:35:10.0",
	schema_name:"Default",
	version:null,
	versions_offset:0,
	failed:0.00,
	result:"Green",
	external_schema:"public",
	description:"DATA_QUALITY_RULE=Collibra Rule;DIMENSION=Completeness;DESCRIPTION=Test it out",
	rule_category_id:0.00,
	rows_failed:0.00,
	table_version:9,
	rule_category:null,
	external_table_name:"PEOPLE",
	included:"Yes"
}